version: '3.7'
services:
  # 1. База даних для Keycloak
  keycloak-db:
    image: postgres:14
    container_name: keycloak_postgres_db
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
    ports:
      - "5433:5432" # Використовуємо 5433, щоб не конфліктувати з іншими БД
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data

  # 2. Сервер Keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.6
    container_name: keycloak_server
    command: start-dev --import-realm
    environment:
      - KC_DB=postgres
      - KC_DB_URL_HOST=keycloak-db
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
      - KC_HEALTH_ENABLED=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "7777:8080"
    volumes:
      - ./game-realm.json:/opt/keycloak/data/import/game-realm.json:Z
    depends_on:
      - keycloak-db
  games-db:
    image: postgres:14
    container_name: games_postgres_db
    environment:
      - POSTGRES_USER=quarkus
      - POSTGRES_PASSWORD=quarkus
      - POSTGRES_DB=gamedb
    ports:
      - "5440:5432"
    volumes:
      - games-db-data:/var/lib/postgresql/data
  players-db:
    image: postgres:14
    container_name: players_postgres_db
    environment:
      - POSTGRES_USER=quarkus
      - POSTGRES_PASSWORD=quarkus
      - POSTGRES_DB=playersdb
    ports:
      - "5441:5432"  # Увага: Зовнішній порт 5441
    volumes:
      - players-db-data:/var/lib/postgresql/data
# 5. Kafka (Message Broker)
  kafka:
    image: docker.io/redpandadata/redpanda:v22.2.1
    container_name: redpanda
    ports:
      - "9092:9092"
    command:
      - redpanda
      - start
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --overprovisioned
      - --node-id 0
      - --check=false
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://kafka:29092,OUTSIDE://localhost:9092
volumes:
  keycloak-db-data:
  games-db-data:
  players-db-data: